In [35]:
import pandas as pd
import matplotlib as plt
import re
import numpy as np

In [53]:
df = pd.read_csv("./df_organizado.csv", sep= ',')

# Filtrando apenas 'credito'
df_credito = df[df['tipo_transacao'] == 'credito']

df_credito.to_csv('credito_movimentacoes.csv', index=False)

In [55]:
df = pd.read_csv("./credito_movimentacoes.csv", sep= ',')

df['tipo_credito'] = df.apply(lambda row: row['info'].split('_')[0] if row['tipo_transacao'] == 'credito' else None, axis=1)

df['info'] = df['info'].apply(lambda x: '_'.join(x.split('_')[1:]))

df.columns = ['data', 'info', 'valor', 'tipo_transacao','estado','tipo_credito']

df.head(10)

,data,info,valor,tipo_transacao,estado,tipo_credito
0,2014-04-30,indexador_pf_tr,1.608026e+10,credito,sc,estoque
1,2014-04-30,carteira_credito_pf_fgts,2.763158e+09,credito,pe,estoque
2,2014-04-30,ltv_pf_comercial,5.537000e+01,credito,pr,contratacao
3,2014-04-30,inadimplencia_pf_sfh,3.280000e+00,credito,ac,estoque
4,2014-04-30,risco_operacao_pf_comercial_aa,9.470000e+00,credito,rs,estoque
5,2014-04-30,risco_operacao_pf_livre_c,3.330000e+00,credito,sc,estoque
6,2014-04-30,indexador_pf_tr,4.932495e+08,credito,ac,estoque
7,2014-04-30,ltv_pf_comercial,6.234000e+01,credito,mg,contratacao
8,2014-04-30,risco_operacao_pj_livre_d_mais,2.330000e+00,credito,ms,estoque
9,2014-04-30,contratado_pf_fgts,2.244158e+08,credito,pr,contratacao

In [33]:
df = pd.read_csv("./df_organizado.csv", sep= ',')
df.head(10)

,data,info,valor,tipo_transacao,estado,tipo_credito
0,2014-04-30,indexador_pf_tr,1.608026e+10,credito,estoque,sc
1,2014-04-30,carteira_credito_pf_fgts,2.763158e+09,credito,estoque,pe
2,2014-04-30,ltv_pf_comercial,5.537000e+01,credito,contratacao,pr
3,2014-04-30,inadimplencia_pf_sfh,3.280000e+00,credito,estoque,ac
4,2014-04-30,risco_operacao_pf_comercial_aa,9.470000e+00,credito,estoque,rs
5,2014-04-30,risco_operacao_pf_livre_c,3.330000e+00,credito,estoque,sc
6,2014-04-30,indexador_pf_tr,4.932495e+08,credito,estoque,ac
7,2014-04-30,ltv_pf_comercial,6.234000e+01,credito,contratacao,mg
8,2014-04-30,risco_operacao_pj_livre_d_mais,2.330000e+00,credito,estoque,ms
9,2014-04-30,contratado_pf_fgts,2.244158e+08,credito,contratacao,pr

In [25]:
# Filtrando apenas as linhas onde 'tipo_transacao' é igual a 'credito'
df_credito = df[df['tipo_transacao'] == 'credito']

# Salvando o DataFrame filtrado em um novo arquivo CSV
df_credito.to_csv('credito_movimentacoes.csv', index=False)